export const USER_ROLE_TEAM_LEAD = 'TEAM_LEAD';

export const USER_ROLE_JUNIOR_DEVELOPER = 'JUNIOR_DEVELOPER';

export const USER_ROLE_SENIOR_DEVELOPER = 'SENIOR_DEVELOPER';

export const USER_ROLE_TESTING_ENGINEER = 'TESTING_ENGINEER';

export const USER_ROLE_DEVOPS_ENGINEER = 'DEVOPS_ENGINEER';